### PR TITLE
Add new page for Known Data Clients

### LINKED ISSUE #514: Add a page of known data clients.

### PR DESCRIPTION
**Pull request by susannasiebert**
Closes #514

### CODE REVIEW

**Review by acoffman — APPROVED** [review]
+1

**Comment by malachig** [comment]
Examples of resources we might add:
- SwissMTB
- Hemap

@sharonfreshour is going to take a pass through citations of our papers to find resources that use DGIdb. 

For each, we want to confirm the resource is alive and uses DGIdb in some way.  Determine a sensible URL to link to.

**Comment by malachig** [comment]
Citations:
[DGIdb V3](https://scholar.google.com/scholar?start=20&hl=en&as_sdt=5,26&sciodt=0,26&cites=12839017266050323662&scipsc=)
[DGIdb V2](https://scholar.google.com/scholar?cites=11118121934715797623&as_sdt=5,26&sciodt=0,26&hl=en)
[DGIdb V1](https://scholar.google.com/scholar?cites=13047653509473595245&as_sdt=5,26&sciodt=0,26&hl=en)

**Comment by sharonfreshour** [comment]
Here's a list of tools and databases that I was able to verify actually use DGIdb data and have some kind of working link:

TCLP (TRON Cell Line Portal) - http://celllines.tron-mainz.de/

GEMINI (GEnome MINIng) - https://gemini.readthedocs.io/en/latest/index.html

PANDA (Pathway AND Annotation) Explorer - http://bioinformaticstools.mayo.edu/research/panda/

Personalized Cancer Therapy - https://pct.mdanderson.org/home

CancerGD - http://www.cancergd.org/

VAReporter - http://rnd.cgu.edu.tw/vareporter/

VarCards - http://varcards.biols.ac.cn/

mTCTScan - http://mulinlab.tmu.edu.cn/mtctscan

CANCROX - http://cancrox.gmb.bio.br/view/index.php

CSgator - http://csgator.ewha.ac.kr/

GMIEC (a shiny app) - https://github.com/guidmt/GMIEC-shiny

CoDReS - http://bioinformatics.cing.ac.cy/codres/

theRING - https://precious.polito.it/theringdb/home

Notes on a couple other sources:
SwissMTB - datasets only available by request
Hemap - paper mentions dgidb, but I can't find a mention or link outs or anything on the website
NCG (Network of Cancer Genes, http://ncg.kcl.ac.uk/) links to DGIdb, but link outs give an error about needing to search at least one gene

**Comment by susannasiebert** [comment]
I think we should still list to the last three. For SwissMTB we could link to the paper (I don't think the resource itself has a public link). For Hemap we could either link to the paper or to http://hemap.uta.fi/hemap/index.html. I think we should still link to NCG with the link you found but we should contact them to (1) get the linkout url updated from dgidb.genome.wustl.edu to dgidb. org and to (2) fix the way to link is constructed.

**Comment by kcotto** [comment]
I agree with Susanna on linking to the last three as well. I can reach out to NCG to discuss fixing those linkouts unless someone else would rather do it.

**Pull request merged**
