### PR TITLE
New online updater for Guide to Pharmacology

### PR DESCRIPTION
**Pull request by susannasiebert**
This online updater is currently very slow since it has to make multiple API calls for each claim we want to create. I'm happy to incorporate any suggestions as to how to speed it up, if possible.

I've tried running it twice so far and both times it failed about 5-6 hours in because a API request failed. From the description it isn't clear to me if it failed because of some intermittent server issue or what.

Alternatively, we could go back to using the tsv importer and wrapping it in our online updater functionality (probably rewriting the tsv importer in the process).

### CODE REVIEW

**Comment by susannasiebert** [comment]
Part of the reason that this is so long-running is that there are over 13000 interactions to import.

**Comment by ahwagner** [comment]
Hrm. I don't like the idea of hammering the server with multiple requests for each of 13K interactions. I agree that we should go to an online tsv importer.

**Comment by susannasiebert** [comment]
I changed this updater to be tsv-based. It imports fine but drug grouping fails. @ahwagner would you have time to look into that? It didn't see anything obvious.

**Comment by susannasiebert** [comment]
I think I just needed to run `rake dgidb:load_local`.

**Comment by susannasiebert** [comment]
This are the stats after grouping:
```
 gene_claims_count: 1608,
 drug_claims_count: 6495,
 interaction_claims_count: 12593,
 interaction_claims_in_groups_count: 7876,
 gene_claims_in_groups_count: 1573,
 drug_claims_in_groups_count: 3822,
```

**Comment by ahwagner** [comment]
👍

**Pull request merged**
