### PR TITLE
Category view

### PR DESCRIPTION
**Pull request by yanyangfeng**
addresses #283

### CODE REVIEW

**Comment by kcotto** [comment]
Something weird is happening on the by category page. It appears it's not showing all of the druggable gene categories that have a result in them. The live site shows 16 druggable gene categories but I'm only seeing 11 on this when viewing that tab on this PR.

Also, do we want to consider sorting the druggable gene categories either alphabetically or ordering by the number of genes from the query within them?

**Comment by yanyangfeng** [comment]
I'll sort the by category results by number of genes and leave browse categories in alphabetical order.

I'm currently looking into the by category issue - I'm seeing the same thing, but I'm wondering if this is a database thing?

**Comment by yanyangfeng** [comment]
seems like there is a view bug and just an underlying difference in the database.

**Comment by yanyangfeng** [comment]
The visual bug is fixed, pushing commit to this PR. 

There doesn't appear to be anything funky going on, assuming my db is in the state we want it. I went through psql and ran SELECT * FROM genes INNER JOIN gene_categories_genes ON genes.id = gene_categories_genes.gene_id INNER JOIN gene_claim_categories on gene_categories_genes.gene_claim_category_id = gene_claim_categories.id WHERE genes.name=<gene> for each of the uniquely matching genes in the example search and it looks like all the categories are being represented.

**Comment by kcotto** [comment]
screen shot 2017-10-06 at 3 39 05 pm

I can see all of the results now. However, I'm still not seeing any sort of sorting on this tab, either by alphabetically or by the number of results.

**Pull request merged**
