### PR TITLE
Fix interaction bug

### PR DESCRIPTION
**Pull request by ahwagner**
This branch seems to be for issue #112. @gspies, is this ready for code review?

### CODE REVIEW

**Comment by ahwagner** [comment]
this PR addresses issues #115 and #112

**Comment by ahwagner** [comment]
Fix for #115 looks good.

**Comment by ahwagner** [comment]
fix for #112 will be addressed in a separate PR. +1 for #115 fix.

**Comment by acoffman** [comment]
@ahwagner this appears to be two unrelated changes. The fix for #115 and some changes to the importer. We don't need the importer changes AFAIK and this https://github.com/griffithlab/dgi-db/pull/116 PR contains just the drug fix we want. I think we should close this one and merge the other. Thoughts?

**Comment by ahwagner** [comment]
Agreed.

**Pull request closed without merging**
